numeros = [1, 2, 3]
letras = ["a", "b", "c"]
palabras = ["feo", "ql"]
maspalabras = ["feo", "ql", "te", "quiero", "mucho"]
booleans = [True, False, False]
matriz = [[0, 1], [1, 0]]
ceros = [0, 1] * 10
alfanumerico = numeros + letras
rango = list(range(1, 11))
chars = list("hola mundo")
